spring.application.name=movieapp
server.port=8084
spring.datasource.url=jdbc:mysql://localhost:5433/movie_db
spring.datasource.username=root
spring.datasource.password=suyash

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false