spring.application.name=springassignemt-1
spring.datasource.url=jdbc:postgresql://localhost:5432/mappingDb
spring.datasource.username=postgres
spring.datasource.password=tiger
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.main.allow-bean-definition-overriding=true

server.port=8084